name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: old-cv-kulerock
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ROLE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ROLE_SECRET_KEY }}
          SOURCE_DIR: ./CV
  readme-to-pdf:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Install Pandoc and LaTeX dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc texlive texlive-latex-extra texlive-xetex
  
      - name: Convert README.md to PDF
        run: pandoc --from markdown --to pdf README.md -o README.pdf --template=template.tex
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: README.pdf
          path: README.pdf




  
